services:
  workspace:
    # node:20-bullseye
    image: mcr.microsoft.com/vscode/devcontainers/javascript-node:20-bullseye
    # init: コンテナの起動時に実行されるコマンド
    init: true
    # command: コンテナの起動時に実行されるコマンド
    command: /bin/sh -c "mkdir -p /home/node/dev; tail -f /dev/null"
    # extra_hosts: コンテナのホスト名を追加
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # volumes: ホストのディレクトリをコンテナにマウント
    volumes:
      - ..:/home/node/dev:cached
      - ~/.ssh/id_rsa.pub:/home/node/.ssh/id_rsa.pub:ro
      - ~/.ssh/id_rsa:/home/node/.ssh/id_rsa:ro
    # working_dir: コンテナの作業ディレクトリ
    working_dir: /home/node/dev
